server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  supportedCountries:
    - AR
    - BR
    - CO
    - MX
    - PY
    - US

message:
  rabbitmq:
    domain: order
    actions: create, update
    exchange: order.command.exchange