server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/${spring.data.mongodb.database}?authSource=admin
      database: database-order
      collectionName: Order

app:
  supportedCountries:
    - AR
    - BR
    - CO
    - MX
    - PY
    - US

message:
  rabbitmq:
    domain: order
    actions:
      - create
      - update
    exchange: order.command.exchange