name: CI Consumer

on:
  pull_request:
    branches:
      - main

jobs:
  build-consumer:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.3-eclipse-temurin-17
      env:
        RABBITMQ_HOST: rabbitmq

    services:
      rabbitmq:
        image: rabbitmq:3-management
        options: >-
          --health-cmd="rabbitmq-diagnostics -q ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean install -DskipTests -f consumer/pom.xml

      - name: Run unit tests
        run: mvn test -f consumer/pom.xml

      - name: Run Spring Boot Consumer with CI config
        run: |
          export RABBITMQ_HOST=rabbitmq
          mvn spring-boot:run -Dspring-boot.run.profiles=ci -Dspring-boot.run.main-class=com.ppm.delivery.order.consumer.PpmDeliveryOrderConsumerApplication -f consumer/pom.xml
