name: CI Producer

on:
  pull_request:
    branches:
      - main

jobs:
  build-producer:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.3-eclipse-temurin-17

    services:
      rabbitmq:
        image: rabbitmq:3-management
        options: >-
          --health-cmd="rabbitmq-diagnostics -q ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Run unit tests
        run: mvn -B test

      - name: Validate Spring Boot startup
        run: |
          echo "Waiting for RabbitMQ to be ready..."
          for i in {1..30}; do
            if docker exec $(docker ps --filter "ancestor=rabbitmq:3-management" --format "{{.ID}}") rabbitmq-diagnostics -q ping >/dev/null 2>&1 || true; then
              echo "RabbitMQ is ready!"
              break
            fi
            sleep 5
          done

          echo "Starting Spring Boot Producer..."
          mvn spring-boot:run -Dspring-boot.run.main-class=com.ppm.delivery.order.producer.PpmDeliveryOrderProducerApplication > spring-boot.log 2>&1 &
          SPRING_PID=$!

          echo "Waiting for Spring Boot to open port 8080..."
          for i in {1..30}; do
            if nc -z localhost 8080; then
              echo "Spring Boot is up!"
              break
            fi
            sleep 1
          done

          if ! nc -z localhost 8080; then
            echo "Spring Boot failed to start in 30 seconds"
            cat spring-boot.log
            kill $SPRING_PID || true
            exit 1
          fi

          kill $SPRING_PID || true
        shell: bash



